org: sampreethamith65
app: ci-cd-express-api
service: ci-cd-express-api

frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: "20201221"
  stage: dev
  environment:
    NAME: ${NAME: NAME}
    AGE: ${AGE: AGE}

functions:
  api:
    handler: handler.handler
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{proxy+}
          method: ANY
